### ISSUE TITLE
A file which matches the pattern in multiple ways is returned multiple times

### ISSUE THREAD

**Issue by robvanuden** [kthompson/glob#52] opened 2019-07-02 08:38 UTC
Suppose I have the following file:
`C:\files\a\a\a\b.txt`
When I use the following code:
`string[] matchingFiles = Glob.Files(@"C:\files", "**/a/**/b.txt").ToArray();` 
`matchingFiles` result is:
```
[0] = a\a\a\b.txt
[1] = a\a\a\b.txt
[2] = a\a\a\b.txt
```

When I add another `a\` subfolder, it gets another item added etc.

Is this by design? I would rather get distinct values.

**Comment by kthompson** [comment] 2019-07-02 15:09
No this is definitely not intentional. I will see if i can determine the cause.

**Comment by robvanuden** [comment] 2019-07-04 11:53
@kthompson I'm new to this code, but when I append `.Distinct()` to [this line](https://github.com/kthompson/glob/blob/5f2feb12fa91f6633a89e601cd683b62e3511cc7/src/Glob/PathTraverser.cs#L68) it's working correctly.
I'm not sure if that is how you want to fix it, so didn't create a PR yet...

**Comment by kthompson** [comment] 2019-07-04 15:10
That would be one way to solve it but I am wondering if there is a way to prevent the traversal.

How would you suggest refactoring that would enable PathTraverser to prevent traversals that result in duplicate results?

**Comment by ffMathy** [comment] 2020-06-27 19:02
How about just using a `HashSet<string>` to store the paths? That way, duplicates won't be stored, and it's `O(1)` insertion time complexity (almost no cost).

**Comment by kthompson** [comment] 2020-07-03 17:02
Fixed in version 1.1.7

**Closed by kthompson** 2020-07-03 17:02 UTC
Labels: bug
